title: 김동희 개발블로그
description: 개발지
url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
# - title: About
#   url: /about

social:
   #github: donghee0815
   #twitter: brianmaierjr
   #facebook: brianmaierjr
   email: donghee0815@gmail.com
